export const data = [
  {
    id: 1,
    name: 'DeadGod#7974',
    price: '19.69 ETH',
    collection: 'Emblem Vault V2',
    description: `This Emblem Vault contains the private keys to a bitcoin wallet which holds Ordinal Inscription #77501, This inscription is part of the https://btc.degods.com/ project.`,
    img: require('../img/dead-god-7974.png'),
  },
  {
    id: 2,
    name: 'MutantApeYachtClub #28270',
    price: '25 ETH',
    collection: 'Mutant Ape Yacht Club',
    description: `The MUTANT APE YACHT CLUB is a collection of up to 20,000 Mutant Apes that can only be created by exposing an existing Bored Ape to a vial of MUTANT SERUM or by minting a Mutant Ape in the public sale.`,
    img: require('../img/mutant-ape-yacht-club-28270.png'),
  },
  {
    id: 3,
    name: 'CloneX#2348',
    price: '8 ETH',
    collection: 'Clone X',
    description: `20,000 next-gen Avatars, by RTFKT and Takashi Murakami 🌸
If you own a clone without any Murakami trait please read the terms regarding RTFKT - Owned Content here: https://rtfkt.com/legal-2A`,
    img: require('../img/clonex-2348.png'),
  },
  {
    id: 4,
    name: 'CoolCat#1465',
    price: '2.45 ETH',
    collection: 'Cool Cat',
    description: `Cool Cats is a collection of 9,999 randomly generated and stylistically curated NFTs that exist on the Ethereum Blockchain. Cool Cat holders can participate in exclusive events such as NFT claims, raffles, community giveaways, and more....`,
    img: require('../img/cool-cat-1465.png'),
  },
  {
    id: 5,
    name: 'LilPudgy#5008',
    price: '0.443 ETH',
    collection: 'Lil Pudgys',
    description: `Lil Pudgys are a collection of 22,222 randomly generated NFTs minted on Ethereum. `,
    img: require('../img/lil-pudgy-5008.png'),
  },
  {
    id: 6,
    name: 'CloneX#1791',
    price: '51.02 ETH',
    collection: 'Clone X',
    description: `20,000 next-gen Avatars, by RTFKT and Takashi Murakami 🌸 If you own a clone without any Murakami trait please read the terms regarding RTFKT - Owned Content here: https://rtfkt.com/legal-2A`,
    img: require('../img/clonex-1791.png'),
  },
  {
    id: 7,
    name: 'BoredApeYachtClub#4719',
    price: '78.56 ETH',
    collection: 'Bored Ape Yacht Club',
    description: '',
    img: require('../img/bored-ape-yacht-club-4719.png'),
  },
  {
    id: 8,
    name: 'Otherdeed#83612',
    price: '49 ETH',
    collection: 'Otherdeed',
    description: '',
    img: require('../img/otherdeed-83612.png'),
  },
  {
    id: 9,
    name: 'Otherdeed#49557',
    price: '19 ETH',
    collection: 'Otherdeed',
    description: '',
    img: require('../img/otherdeed-49557.png'),
  },
  {
    id: 10,
    name: 'RENGA#6870',
    price: '2.95 ETH',
    collection: 'RENGA',
    description: '',
    img: require('../img/renga-6870.png'),
  },
  {
    id: 11,
    name: 'Azuki#6057',
    price: '16.02 ETH',
    collection: 'Azuki',
    description: '',
    img: require('../img/azuki-6057.png'),
  },
  {
    id: 12,
    name: 'Bean#4355',
    price: '1.969 ETH',
    collection: 'Bean',
    description: '',
    img: require('../img/bean-4355.png'),
  },
];
